#!/bin/bash -i

exec--main() {
  local cmd=`basename $0`
  declare -F | grep exec-- | sed 's/declare -f exec/'$cmd' /'
}

SETUPDIR=$( dirname $(realpath "$0") )
. $SETUPDIR/bash/common.sh
module=$(basename $PWD)
definedcallbacks=$($SETUPDIR/index.js $module -h | grep -o -h "[[:alpha:]]*--[[:alpha:]-]*" | tr '\n' ' ')
callback="$1"
shift
if [[ " ${definedcallbacks[@]} " =~ " ${callback} " ]]; then
  arg=$(addQuote "$@")
  cmd="$SETUPDIR/index.js $module $callback $arg"
  echo "[Info][Exec] via node. $cmd"
  eval $cmd
else
  oliver-common-exec "$@"
fi
